[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
curachain = "4t7Agar7zuPB4o6mit6jijt6RMuRdKtqE8FYRybApbBj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
